ELASTIC_HOST = 'localhost'
ELASTIC_PORT = 9200
ELASTIC_USER = False
ELASTIC_PASSWORD = False

POSTGRESQL_HOST = 'localhost'
POSTGRESQL_PORT = 5432
POSTGRESQL_USER = 'postgres'
POSTGRESQL_PASSWORD = False

GEONAMES_USERNAME = ''
